version: "3.8"
services:
    postgres:
        container_name: postgres
        build:
            context: ./postgres
    backend:
        container_name: backend
        restart: always
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=postgres
            - METRICS_USER=admin
            - METRICS_PASSWORD=admin
        build:
            context: ./backend
    prometheus:
        container_name: prometheus
        build:
            context: prometheus
    grafana:
        container_name: grafana
        build:
            context: grafana
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"