version: '3'
services:
  burpsuite:
    image: hexcowboy/burpsuite
    ports:
      - "8080:8080"
    environment:
      #DISPLAY: host.docker.internal:0
      DISPLAY: 192.168.1.133:0
      #DISPLAY: 127.0.0.1:0
      #DISPLAY: :0
    #volumes:
    #  - /tmp/.X11-unix:/tmp/.X11-unix